require('jquery/dist/jquery.slim')
// require('goratchet/dist/js/ratchet.js')
require('goratchet/dist/css/ratchet.css')
const devtools = require('choo-devtools')
const choo = require('choo')
const store = require('./store/index.js')
const layout = require('./components/layout')
const home = require('./components/home')
const challenges = require('./components/challenges')
const settings = require('./components/settings')
const login = require('./components/login')

const app = choo()
app.use(devtools())
app.use(store)
app.route('/', layout(home))
app.route('/challenges', layout(challenges))
app.route('/settings', layout(settings))
app.route('/login', login)
app.mount('#app-root')
