require('jquery/dist/jquery.slim')
require('popper.js/dist/popper.js')
require('bootstrap/dist/js/bootstrap.js')
const devtools = require('choo-devtools')
const choo = require('choo')
const store = require('./store/index.js')
const auth = require('./auth')
const home = require('./components/home')
const login = require('./components/login')

const app = choo()
app.use(devtools())
app.use(store)
app.use(auth)
app.route('/', home)
app.route('/login', login)
app.mount('#app-root')
